<?php

return array(
  'proca_login' => array(
    'name' => 'proca_login',
    'type' => 'String',
    'html_type' => 'text',
    'add' => '4.7',
    'title' => ts('Login on Proca site'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('login on proca site'),
    'settings_pages' => ['proca' => ['weight' => 10]],
  ),
  'proca_password' => array(
    'name' => 'proca_password',
    'type' => 'String',
    'html_type' => 'text',
    'add' => '4.7',
    'title' => ts('Password on proca site'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('password on proca site'),
    'settings_pages' => ['proca' => ['weight' => 10]],
  ),
  'proca_org' => array(
    'name' => 'proca_org',
    'type' => 'String',
    'html_type' => 'text',
    'add' => '4.7',
    'title' => ts('(short) name of the organisation on proca'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['proca' => ['weight' => 10]],
  ),
  'proca_public_key' => array(
    'name' => 'proca_public_key',
    'type' => 'String',
    'html_type' => 'text',
    'add' => '4.7',
    'title' => ts('public key - if encryption set'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['proca' => ['weight' => 10]],
  ),
  'proca_private_key' => array(
    'name' => 'proca_private_key',
    'type' => 'String',
    'html_type' => 'text',
    'add' => '4.7',
    'title' => ts('private key - if encryption set'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['proca' => ['weight' => 10]],
  ),
  'proca_limit' => array(
    'name' => 'proca_limit',
    'type' => 'Int',
    'html_type' => 'text',
    'add' => '4.7',
    'title' => ts('batch size, how many to load'),
    'default' => 1000,
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['proca' => ['weight' => 10]],
  ),
  );
